### ISSUE TITLE
Cargar archivo python primera parte

### ISSUE THREAD

**Issue by programacioncarolina1980** [CodeSystem2022/UTENIANOS_Tercer_Semestre#50]
Se carga  primera parte de código en lenguaje python de proyecto de verificador de precios con descuento

**Comment by agussputrii** [comment]
Parte 1: Menú de ingreso de compras

Funciones: main(), menuIngresoDeCompras(), validacionCantidadArticulos(), validacionPrecioArticulo()
Propósito: Recopila la cantidad de artículos y los precios unitarios de los productos comprados, calcula el importe total de la compra y muestra el resultado.

Estas tareas se han completado en la primera parte del desarrollo y se han verificado su funcionamiento.
