### ISSUE TITLE
Cargar archivo python segunda parte

### ISSUE THREAD

**Issue by programacioncarolina1980** [CodeSystem2022/UTENIANOS_Tercer_Semestre#51]
Se cargan archivos de asegunda parte de proyecto Integrador tercer semestre del Verificador de precios con descuento de equipo Utenianos en carpeta python

**Comment by Hiddencelc** [comment]
Funciones: menuDeConfirmacion(), menuDescuento(), calcularDescuento()
Propósito: Permite al usuario seleccionar diferentes opciones, como ir a la pantalla de descuentos, volver al menú de compras o salir del programa. Además, calcula y muestra el descuento aplicado según el día de la semana.
