### ISSUE TITLE
Cargar archivo python tercera parte

### ISSUE THREAD

**Issue by programacioncarolina1980** [CodeSystem2022/UTENIANOS_Tercer_Semestre#52]
Se cargarán archivos python de tercera parte del Proyecto Integrador "Verificador de precio con descuento de tercer semestre en carpeta python del equipo Utenianos

**Comment by jsaba543** [comment]
Cargada parte nº 3 del Proyecto Integrador UTENIANOS. Función Principal y punto de entrada
