### ISSUE TITLE
Prueba ,creación de etiqueta prueba exitosa y cierre del proyecto

### ISSUE THREAD

**Issue by programacioncarolina1980** [CodeSystem2022/UTENIANOS_Tercer_Semestre#53]
Prueba y  cierre de proyecto Integrador de tercer semestre del verificador de precios con descuento  con etiqueta.

**Comment by MiriamTorres30** [comment]
Prueba exitosa de proyecto verificador de precios con descuento

**Comment by MiriamTorres30** [comment]
Se realizó la prueba
