### ISSUE TITLE
Creación de las carpetas de los distintos lenguajes: java, pyton y Js.

### ISSUE THREAD

**Issue by Hiddencelc** [CodeSystem2022/UTENIANOS_Tercer_Semestre#57]
Se crearon carpetas y subcarpetas en lenguaje python, java y javascript solicitados para semana 10 en el equipo Utenianos

**Comment by programacioncarolina1980** [comment]
Se crean carpetas

**Comment by Hiddencelc** [comment]
tarea completada: se procedió a probar el código.
